### ISSUE TITLE
altice

### ISSUE THREAD

**Issue by avico78** [queimadus/fgw_router#2]
Have altice router FGW Software version 3GN8020300r23
will this work with latest HA version?
I added as in the device_trackert.yaml
```

  - platform: fgw_router
    host: 192.168.1.1
    port: 80
    username: aaaaaa
    password: xxxxxxx
      
```
but doesnt work, nothing appear in known_devices.yaml
can u provide more information for how to use it?

**Comment by queimadus** [comment]
Hi @avico78, is your `configuration.yaml` including the `device_tracker.yaml` file?

Can you try to add those settings directly to the `configuration.yaml`?

```yaml
device_tracker:
  - platform: fgw_router
    host: 192.168.1.254
    port: 23
    username: !secret fgw_router_username
    password: !secret fgw_router_password
    interval_seconds: 60
```

If that doesn't work, have you installed this integration correctly or are you getting errors like "fgw_router does not exist"?
